name: 校验 Fastlane 元数据

on:
  workflow_dispatch:
  push:
      branches: [ "main" ]
      paths:
        - 'fastlane/**'
  pull_request:
      branches: [ "main" ]
      paths:
        - 'fastlane/**'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: 校验 Fastlane Supply 元数据
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2.1.0
